name: Generate contribution snake

on:
  schedule:
    # Rebuild every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Generate contribution-graph snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: pbathuri
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#0D1117,#161B22,#FFA657,#58A6FF,#E6EDF3

      - name: Push generated output to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
